### ISSUE TITLE
struggling to get nice!view working

### ISSUE THREAD

**Issue by pashashocky** [raeedcho/chocofi-temper#26]
Trying to get nice!view to work with miryoku, the displays don't currently turn on do I need to do something special?

tried all the below
```
name: 'Build temper nice_nano_v2 nice_view'
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["temper_left nice_view_adapter nice_view","temper_right nice_view_adapter nice_view"]'
      custom_config: '["#define MIRYOKU_ALPHAS_QWERTY\n#define MIRYOKU_EXTRA_COLEMAKDH\n#define MIRYOKU_KLUDGE_MOUSEKEYSPR"]'
      kconfig: '["CONFIG_ZMK_SLEEP=y\nCONFIG_ZMK_MOUSE=y"]'
```

```
name: 'Build temper nice_nano_v2 nice_view'
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["temper_left nice_view","temper_right nice_view"]'
      custom_config: '["#define MIRYOKU_ALPHAS_QWERTY\n#define MIRYOKU_EXTRA_COLEMAKDH\n#define MIRYOKU_KLUDGE_MOUSEKEYSPR"]'
      kconfig: '["CONFIG_ZMK_SLEEP=y\nCONFIG_ZMK_MOUSE=y"]'
```

```
name: 'Build temper nice_nano_v2 nice_view'
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["temper_left nice_view_adapter nice_view","temper_right nice_view_adapter nice_view"]'
      custom_config: '["#define MIRYOKU_ALPHAS_QWERTY\n#define MIRYOKU_EXTRA_COLEMAKDH\n#define MIRYOKU_KLUDGE_MOUSEKEYSPR"]'
      kconfig: '["CONFIG_ZMK_SLEEP=y\nCONFIG_ZMK_MOUSE=y\nCONFIG_ZMK_DISPLAY=y"]'
```
